### ISSUE TITLE
Current v2 version numbering

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#1]
The current version number in the spec should indicate an "immature" status (2.0.1, 2.0.1a ... whatever your flavour @sdelatorrep).

```
info:
  version: "2.0.1a"
```

**Comment by jrambla** [comment]
We discussed that yesterday, but is seems to me that 2.0,1 i saying "this is the first PATCH over the version 2.0.0". 
I guess there should exist a convention for this case.

**Comment by mbaudis** [comment]
@jrambla Well, there are several :-( However, I recommend going with [Semantic Versioning](https://semver.org/#spec-item-9), which in the case of a major-new-version-first-pre-release would result in e.g.`2.0.0-alpha` or `2.0.0-alpha.1`. But we should have it clear that this is pre-release.

**Comment by jrambla** [comment]
Thanks Michael! I was looking for that unsuccesfully. Now you the link you added has refreshed my mind.
@sdelatorrep let's go for ` 2.0.0-draft.1 ` until we believe it should be `alpha `
