### ISSUE TITLE
Add "url" and remove "id" from "receivedRequest"

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification-v2#11]
Imagine we are requesting a specific individual by calling `/individuals/IND1111`.
In the response, we could have this new field `url` within `receivedRequest`:
```json
{
    "receivedRequest": {
      "url": "/individuals/IND1111",
      "meta": {
        "requestedSchemas": { }
      },
      "query": { }
    }
}
```
instead of:
```json
{
    "receivedRequest": {
      "meta": {
        "requestedSchemas": { }
      },
      "query": {
        "individual": {
          "id": "IND1111"
        }
      }
    }
}
```
We can get rid of these complex objects, `individual` and `biosample`, and the `id` field within them and `g_variant`.

**Comment by jrambla** [comment]
As agreed, not doing any change. Thanks.
