### ISSUE TITLE
Undefined property in RequestQeury

### ISSUE THREAD

**Issue by MalinAhlberg** [ga4gh-beacon/specification-v2#18]
Hi,

I tried to parse the spec, but got an error.
This [line](https://github.com/ga4gh-beacon/specification-v2/blob/master/beacon.yaml#L901) mentions `query` as being required, although it is not among the properties. I'm not sure whether it should be removed from the `required` list or added to the `properties` list?

**Comment by sdelatorrep** [comment]
Hi Malin!
It's a copy and paste error, haha I've just fixed it. 
Thanks for spotting this!
