### ISSUE TITLE
YAML formatting

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#2]
I have suggestions for the formatting of the spec file:

1. using a consistent style for descriptions; I recommend _always_ to use the multi-line format (with the sole exception of single word comments).
2. Use Markdown style to structure multi-line descriptions:
```
        start:
          description: |
            Precise or fuzzy start coordinate position(s), allele locus (0-based, inclusive).
            * start only:
              - for single positions, e.g. the start of a specified sequence
              alteration where the size is given through the specified
              alternateBases
            * `start` and `end`:
...
```
3. follow the Google code documentation style & break lines in comments at 80 chars

**Comment by sdelatorrep** [comment]
+1

**Comment by jrambla** [comment]
Can we close the issue or there is anything pending to be done?

**Comment by jrambla** [comment]
As noone is objecting I'll consider this issue "solved".
