### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by teemukataja** [ga4gh-beacon/specification-v2#20]
I suggest that the specification should **enforce** [semantic versioning](https://semver.org/).

In this case the only valid way to state version would be a string with digits separated by periods: `MAJOR.MINOR.PATCH`, e.g. `2.0.0`. The version shouldn't contain any other characters, like a leading `v` e.g. `v2.0.0`.

This would make the version easier to handle programmatically, as we could trust, that services express this information in a uniform way.

**Comment by jrambla** [comment]
Yes, we are trying to follow that approach. Thanks!
