### ISSUE TITLE
Replace Chromosome

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#22]
As discussed previously, the use of (hard coded) `Chromosome` is a limiting design (which had already been mentioned in the original Beacon design discussions in 2014). Changing this had also been the topic of a recent recommendation by members of the GKS team.

##### Proposal:

* change to  "accession.version" of a chromosome, e.g. `NC_0000015.10`
* document use of chromosome by short name + assembly id for front-end use ("GRCh38" & "15")

**Comment by jrambla** [comment]
The issues here are which names are intuitive enough and academically correct enough to indicate the reference and the chromosome/contig inside that reference. 
"GRCh38" & "15" seems much more intuitive that NC_0000015.10

**Comment by mbaudis** [comment]
@jrambla Intuitively & from common use I agree. However, then a mechanism is needed to validate and/or translate these combinations. You may have solved this in the COVID19 use case already (we - that is @qingyao - have been struggling to find the correct syntax there for ours ...).

So: This needs a documented design, with referencing alternative approaches (e.g. GA4GH VRS).

**Comment by jrambla** [comment]
We plan to engage in this discussion and take a decission in draft4
