### ISSUE TITLE
Use IUPAC nucleotide codes

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#23]
The use of [IUPAC nucleotide codes ](https://www.bioinformatics.org/sms/iupac.html) would provide a more flexible way to query for precise sequence alterations, instead of having only specific nucleotide codes or `N`.

This protocol enhancement is backwards compatible (`N` is an IUPAC code).

Additionally, this approach would be in line with the “use external standards wherever possible” concept.

IUPAC nucleotide code | Base
-- | --
A | Adenine
C | Cytosine
G | Guanine
T (or U) | Thymine (or Uracil)
R | A or G
Y | C or T
S | G or C
W | A or T
K | G or T
M | A or C
B | C or G or T
D | A or G or T
H | A or C or T
V | A or C or G
N | any base
. or - | gap

**Comment by jrambla** [comment]
We've been discussing that in the context of [https://covid19beacon.crg.eu/](https://covid19beacon.crg.eu/), as many viral consensus sequences use the UIPAC codes. 
It seems to make implementation a little bit more complex and less performant (as "OR" boolean operators apply), and we were wondering how much they will actually be used in reality.. 
@sdelatorrep something to bring to the GA4GH Beacon call.

**Comment by mbaudis** [comment]
@jrambla Since `N` is already allowed one has to regex in case of its occurrence.

For example, our practical implementation is currently:

* if no `N` in ...bases => exact match
* if only `N` -> by convention one or more unspecified bases => doesn't need a lookup
* if `N` and others => regex:
```
            if "N" in variant_pars[ p ]:
                rb = variant_pars[ p ].replace("N", ".")
                v_q_p.append( { p_n: { '$regex': rb } } )
```
(The "p" there is for `[ "referenceBases", "alternateBases" ]`; `v_q_p` is the list of queries).
This would be similar with a IUPAC lookup table:
```
for iupac in iupac_codes:
    if iupac in variant_pars[ p ]:
        rs = "["+"".join(iupac_codes[iupac])+"]"
        rb = variant_pars[ p ].replace(iupac, rs)
        v_q_p.append( { p_n: { '$regex': rb } } )
```
... or such; e.g. `"referenceBases": "AHT"` => `'$regex': "A[ACT]T"`.

**Comment by jrambla** [comment]
I'm still hesitating, the impact in performance seems quite significative and the return seems not broadly applicable.
To me the question is still open: How many Beacon are having nucleotide codes outside ACTGN? 
@antbro any opinion here?

**Comment by antbro** [comment]
I don't think many Beacons will use codes outside ACTGN

But if this is just about how queries are stated, then performance could be improved by first checking whether the query includes other base codes, and on the rare occasions that it does then duplicate the query once for each two-allele code OR only use IUPAC methods when needed.

Its a bit of a hack, but practical.

The alternative of not allowing IUPAC at all feels wrong

Tony

 Professor Anthony J Brookes
 Department of Genetics & Genome Biology
 University of Leicester
 University Road
 Leicester, LE1 7RH, UK
 Tel: +44 (0)116 2523401
 Mbl: +44 (0)777 0620396
 Fax: +44 (0)116 2523378
 mailto: ***@***.******@***.***>
 --
 ** Where is the wisdom we have lost in knowledge?
 ** Where is the knowledge we have lost in information?
 ** T.S. Eliot

________________________________

**Comment by jrambla** [comment]
@sdelatorrep or @MrRobb could you do a PR on this?

**Comment by antbro** [comment]
Could the query state if it uses any IUPAC code other than TCGAN
And services optionally not respond to those that do?
Tony

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jrambla** [comment]
In draft4, we need to find an elegant solution for this issue.
