### ISSUE TITLE
Defining g_variants request types.

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#25]
For versions including 1.n only a single method (`BeaconAlleleRequest`) was used with varying sets of parameters to enable different query scenarios. This led to some confusion and problems in determining the appropriate handling depending on the submitted combination of parameters.
While we tried to address this problem through documentation, for v2 we've agreed to introduce "request types" with clearly designed sets of parameters.

The document below is a proposal for a first set of genomic request types.

```
BeaconRequestTypes:

  g_variant:

    variantIdRequest:
      description:
        A query for a specific variant by its `id`.
      all_of:
        - id

    variantAlleleRequest:
      description: |
        This type corresponds to the original BeaconAlleleRequest, in which at a
        specified genome position a query looks for a combination of reference and
        replacement base(s).
      all_of:
        - assemblyId
        - referenceName
        - start
        - referenceBases
        - alternateBases

    variantCNVrequest:
      description: |
        This specific request allows for the bracketed search of genomic variants
        with start and end coordinates and a variant type. in contrast to a
        beaconRangeRequest, the start and end positions of the matched variants 
        have to fall into the (1 base or longer) intervals for start and end,
        respectively (while for the range request variants falling between start
        and end are being matched).
        `start` and `end` parameters are lists of 1 or 2 integers. The most common
        use here would be a use of 2 integers both for start and end, to allow
        fuzzy matching of CNVs and similar variants of imprecise length and
        position.
      all_of:
        - assemblyId
        - referenceName
        - start
        - end
        - variantType

    variantFusionRequest:
      description: |
        This request is similar to the CNV request in using possibly fuzzy
        intervals for start and end of structural variants. However, here the
        "end" position refers to the fusion partner on the same or different
        chromosome as specified through "mateName".
        Conventions:
        * `mateName` can be the same or different to `referenceName`
        * `mateName` is the higher numbered/named chromosome
      all_of:
        - assemblyId
        - referenceName
        - mateName
        - start
        - end

    variantRangeRequest:
      description: |
        The beaconRangeRequest queries variants falling between start and end.
        `start` and `end` parameters should be single values.
      all_of:
        - assemblyId
        - referenceName
        - start
        - end
      optional:
        - variantType
        - referenceBases
        - alternateBases
```

**Comment by jrambla** [comment]
The idea was to have one g_variant end point, supporting all the required parameters, and then use alias to mask the parameters not relevant or to provide default values for them. E.g.
g_variant would support

- assemblyId
- referenceName
- start
- referenceBases
- alternateBases
- end
- variantType
- mateName

For variantAlleleRequest the alias will do: 
- assemblyId
- referenceName
- start
- referenceBases
- alternateBases
- end = _null_
- variantType = _null_ (or _SNP_, depending on what you mean in your text above)
- mateName = _null_

For variantFusionRequest the alias will do: 
- assemblyId
- referenceName
- start
- referenceBases = _null_
- alternateBases = _null_
- end 
- variantType = "_FUSION_"
- mateName

and so on...

**Comment by sdelatorrep** [comment]
I've gone through the OpenAPI docs, and it seems the only way to achieve this is to create different variant requests types and put them inside the `oneOf`.
* These types will inherit from `GenomicVariantFields`, which contains all the fields, but define a different subset of required parameters, and a different description.
```yaml
    VariantAlleleRequest:
      allOf:
      - description: |
          This type corresponds to the original BeaconAlleleRequest, in which at a
          specified genome position a query looks for a combination of reference and
          replacement base(s).
      - required:
          - assemblyId
          - referenceName
          - start
          - referenceBases
          - alternateBases
      - $ref: '#/components/schemas/GenomicVariantFields'
    VariantCNVrequest:
      allOf:
      - description: |
          This specific request allows for the bracketed search of genomic variants
          with start and end coordinates and a variant type. in contrast to a
          beaconRangeRequest, the start and end positions of the matched variants 
          have to fall into the (1 base or longer) intervals for start and end,
          respectively (while for the range request variants falling between start
          and end are being matched).
          `start` and `end` parameters are lists of 1 or 2 integers. The most common
          use here would be a use of 2 integers both for start and end, to allow
          fuzzy matching of CNVs and similar variants of imprecise length and
          position.
      - required:
        - assemblyId
        - referenceName
        - start
        - end
        - variantType
      - $ref: '#/components/schemas/GenomicVariantFields'
```
* In the definition of `g_variant` field in `RequestQuery`, we specify that you have to choose one among these types (including the general one):
```yaml
    RequestQuery:
      description: |
        TBD
      type: object
      properties:
        ...
        g_variant:
          oneOf:
            - $ref: '#/components/schemas/VariantAlleleRequest'
            - $ref: '#/components/schemas/VariantCNVrequest'
            - $ref: '#/components/schemas/GenomicVariantFields'
        ...
```
WDYT? Do you know any other way to do it?

**Comment by mbaudis** [comment]
Yes, I think so. Only we will have different types from the ones used in the write-up, namely

* VariantAlleleRequest
* GenomicRangeQuery
  - anything (w/ optional parameters for type, alleles) overlapping `start` <=> `end`
* GenomicBracketQuery
  - anything (w/ optional parameters for type, alleles) with start and end falling into `[start0, start1]` && `[end0, end1]` intervals
* ...

(Names subject to heated discussion). 

But I'm definitely +1 to allow/propose the typing of requests, using pre-defined components.

**Comment by sdelatorrep** [comment]
Yes, I'm also in. 
The SV Scout is working on this, right? In defining this list of variant query types, I mean, including examples.

**Comment by mbaudis** [comment]
@sdelatorrep Yes - @babisingh & @laurenfromont working on getting some clean first version based on our previous decisions.

**Comment by jrambla** [comment]
I'm not solid that we must add the aliases to the regular specification. That was not in my mind when the alias were suggested.
I believe that having a parallel spec that is a "façade" over the basic specification would be much more flexible and much clearer to the implementers.

**Comment by jrambla** [comment]
We can explore how easy is to add aliases in the new Framework + Model approach in draft4.
