### ISSUE TITLE
Should `minimum` be part of `items` for "end" type?

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-beacon/specification-v2#27]
https://github.com/ga4gh-beacon/specification-v2/blob/de6cbe8b31659fd0800e6191f9c6d50555759bf3/beacon.yaml#L924-L935

The `minimum` keyword relates to numbers and is not applicable to arrays, which is the type defined for `end`.
I assume this is just a typo and it should be indented further to be part of the `items` schema object.

If it's intended that `end` may be an array or a number, then `integer` should be added to the allowed types.

**Comment by sdelatorrep** [comment]
Fixed. Thanks, @Relequestual!
