### ISSUE TITLE
Proposal: Return REST paths as handover URLs in Beacon responses

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#33]
The current specification implements dedicated paths for scoped data retrieval (e.g. `/biosamples/{id}/g_variants` for the variants belonging to a biosample), which can be amended w/ additional query parameters. Additionally, the Beacon can/should provide information about available protocols and paths. However - and especially in a network - the generation of consistent data retrieval queries seems more conceptual than easy to implement.

A complementary approach could be in the delivery of handover objects which represent the supported REST endpoints for a given query:

* a query for genomic variants is executed
* each Beacon creates for its supported endpoints the corresponding URLs and wraps them in handover objects
    - `https://thisbeacon.org/g_variants/__some__id__/individuals/`
    - `https://thisbeacon.org/g_variants/__some__id__/biosamples/`
* these handover objects have canonical types & schemas (https://github.com/ga4gh-beacon/specification-v2-default-schemas/issues/5)
* a Beacon network can aggregate the responses from the corresponding URLs received in the handover objects
* each Beacon can allow or reject those requests, based on the authentication etc.

**Comment by jrambla** [comment]
As mentioned in direct conversations, this is the goal of [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS).
As much as I'm tempted to explore it the sooner the better, I'm believing that this should be the basis for Beacon v3.0, may be.
