### ISSUE TITLE
Genome Coordinate Use and VRS

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#34]
The current use of `referenceBases` and `alternateBases` is partially incorrect when compared to the GA4GH VRS standard. While it is fine for SNVs (i.e. replacement of a single reference base by another base) or compound replacements (e.g. `A > GG`), it is incorrect for simple INDELs, i.e. insertions or deletions of one or more bases w/o change of the surrounding sequence. Here, VRS states (in spirit) that 

* a deletion results in the removal of the reference base(s) and an *empty value* for the replacement
* an insertion happens at a 0-based, 0-length interval w/ empty reference base and representation of the added bases.

This (preferable) use also removes some logical inconsistencies when using VCF-style "anchor" bases for INDEL variants, e.g. regarding the length of variants or their position.

However, this needs some implementation considerations:

* `ReferenceBases.pattern` should change from `^([ACGTN]+)$` to `^([ACGTN]+)?$` or `^([ACGTN]*)?$`
* the same applies to `AlternateBases`
* this should also be propagated to front-end examples and shorthand annotations (e.g. `ATC>A` style should not be used)
* backends should consider alternative searches if containing "anchor-base" annotations
  - `{start: 1234567, referenceBases: "ATC", alternateBases: "A" }` is equal to
  - `{start: 1234568, referenceBases: "TC", alternateBases: "" }`

Discuss, please.

**Comment by mbaudis** [comment]
And gladly accept corrections / refinements @ahwagner ...

**Comment by sdelatorrep** [comment]
Hi @mbaudis. The specification part was changed in PR #41, wasn't it? If so, I suggest closing this.

**Comment by mbaudis** [comment]
Closing since done in https://github.com/ga4gh-beacon/specification-v2/pull/41.
