### ISSUE TITLE
Consider splitting beacon.yaml in multiple files

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification-v2#4]
Current definition is very long (2194). We should consider splitting it in multiple files.
IMO, I'd start splitting the `components.schemas` and the `components.examples` sections into 2 different files and see if this makes it more readable.

**Comment by mbaudis** [comment]
+1 (has been supported by myself on various occasions...)

**Comment by mbaudis** [comment]
@sdelatorrep I just updated the split version (automatic generation, schemas only - not endpoints etc.). Please have a look at the [specification-v2-test-schemas](https://github.com/ga4gh-beacon/specification-v2-test-schemas) and the representation [on the website](https://beacon-project.io/tags/specification.html).

This is considered very "prototype" - however, I'd like to see how we can build on this...

**Comment by jrambla** [comment]
@sdelatorrep is your splitting being visible somewhere?

**Comment by jrambla** [comment]
@mbaudis it would be nice to do this exercise over the draft.2 version.

**Comment by sdelatorrep** [comment]
@jrambla the splitting I mentioned yesterday was done in the Default Schemas repo, not here yet.

**Comment by mbaudis** [comment]
@jrambla @sdelatorrep See above; I had created a draft method for extracting the schemas from the specification and then run the extracted individual schemas through the SchemaBlocks reformatter => see https://github.com/ga4gh-beacon/specification-v2-test-schemas 
This was before Sabela's schema repository & thought as basis for discussion.

**Comment by jrambla** [comment]
The current OpenAPI tooling doesn't seem to help in navigating among different referenced files. Therefore it doesn't seem a big advantatge to me navigating through a looong file vs. navigating a lot of files. 
Any consideration this aspects?

**Comment by mbaudis** [comment]
@jrambla Well I'm not particular to use the OpenAPI tooling :-) 

But i think a good compromise is to have the single master file and then for readability & website the [extracted components](https://beacon-project.io/tags/schemas.html). Not sure if we should do this for the paths, too.

However - can't the spec been split between the paths & components, at least?

**Comment by jrambla** [comment]
Well, I've said OpenAPI, but I was meaning any tool able to work with that format, YAML or JSON and traverse the references...
We separated the default schemas from the main spec, but not all the components. There are still many ;-)
If the actual suggestion is to have a supporting documentation in a website, then that is OK.
If the suggestion is to further split btw paths and components in external files, then my first comment apply.
I don't know, indeed, the impact that using external references is having in the tools that generate code, check validity, etc.
Do anyone know?

**Comment by mbaudis** [comment]
The traversal of external links is standard - i.e. I get errors processing `beacon.yaml` if the references to, or inside, the default schemas don't resolve.

**Comment by mbaudis** [comment]
... but I still don't understand why the components are not in an external file. Same handling, with the exception of disentangling the schemas (=components) from the paths.

I would actually organise all components and schemas in a single repository and have the paths by themselves. And the `beacon.yaml` only for the paths.

**Comment by jrambla** [comment]
Let's finish the spec changes for resulset,etc. and then we will review the separation again.

**Comment by jrambla** [comment]
Solved in the Framework+Model approach and repos
