### ISSUE TITLE
Incorrect URLs in beacon.yaml

### ISSUE THREAD

**Issue by Tom-Shorter** [ga4gh-beacon/specification-v2#40]
The URLs pointing to the default beacon schemas draft 1 repo release within the beacon.yaml file have a typo in, the URLs have draft-1 in but it should be draft.1 instead. 

e.g.

https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/draft-1/default_variant_annotations_schema.yaml#/components/schemas/VariantAnnotations

should be:

https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/draft.1/default_variant_annotations_schema.yaml#/components/schemas/VariantAnnotations

**Comment by sdelatorrep** [comment]
Yes, I know. I released the first draft of default schemas as `draft-1` when it should have been `draft.1`. I renamed the tag, and later realized this broke the references in this repo. My bad! I'll try to fix it asap. 
Thank you for creating this issue, this way I won't forget it :)

**Comment by sdelatorrep** [comment]
This can be closed, as I recovered the original release (named `draft-1`) long time ago in order to not break this.
