### ISSUE TITLE
Variant => GenomicVariant

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#42]
The current schema uses `GenomicVariantResponseContent` etc., but then just `Variant`, `VariantAnnotation`, `VariantReponseResults`:

https://github.com/ga4gh-beacon/specification-v2/blob/aa2476cd44377ac7822c55342c14fe42acc72cb3/beacon.yaml#L1964

I would +1 to use `GenomicVariant` etc.  then, consistently. This does not preclude e.g. providing protein information in annotations; but IMO for querying protein changes which do not refer to genomic alterations we need other objects anyway.

**Comment by jrambla** [comment]
If still valid, this discussion should move into Beacon v2 Model repo
