### ISSUE TITLE
Referenced `VariantInSample` leads to error

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#43]
The referenced `VariantInSample` leads to a validation error:

https://github.com/ga4gh-beacon/specification-v2/blob/aa2476cd44377ac7822c55342c14fe42acc72cb3/beacon.yaml#L2609

> member 'phenotypicEffect' not found in {'ClinicalRelevance': {'description':  ...

Not checked ... but `VariantInSample` anyway should **NOT** have any clinical, phenotypic ... connotations.

**Comment by sdelatorrep** [comment]
Fixed in Default Schemas repo ([commit](https://github.com/ga4gh-beacon/specification-v2-default-schemas/commit/afa5095823c513b54359f929d04c1a2b79cbe2ea)).
