### ISSUE TITLE
Structure of `/filtering_terms` response

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#44]
The `/filtering_terms` response is just a simple object with `beaconId`, `apiVersion` and a list of `filteringTerms` objects.

For consistency, it would make sense to provide the `filteringTerms` in the standard `InfoResponse` wrapper, with `meta` and then `response.results` containing the list of `FilteringTerm` objects.

Fast draft example (incomplete ...):

```
meta:
  api_version: "2.0.0-draft.3",
  beaconId: ...
  returned_schemas:
    FilteringTerm: "https://beacon-project.io/schemas/beacon-v2/current/FilteringTerm.json"
response:
  error: 
    error_code: 0
  exists: true
  info:
    count: 1322
  results:
    - id : "NCIT:C3059"
      label : "Glioma"
    - id : "NCIT:C3716"
      label : "Primitive Neuroectodermal Tumor"
...
```
For reference, current definition below.

```
    FilteringTermsResponse:
      type: object
      description: |
        Filtering terms available in this Beacon.
      required:
        - beaconId
        - apiVersion
        - filteringTerms
      properties:
        beaconId:
          description: |
            Identifier of the beacon, as defined in `Beacon`.
          type: string
        apiVersion:
          description: |
            Version of the API implemented by this Beacon.
          type: string
          example: 'v2.0'
        filteringTerms:
          type: array
          items:
            $ref: '#/components/schemas/FilteringTerm'
```

For previous discussions regarding the format etc. see [this issue](https://github.com/ga4gh-beacon/specification-v2/issues/30).

**Comment by jrambla** [comment]
+1

**Comment by mbaudis** [comment]
@jrambla only +1, for such a descriptive issue? :-)

**Comment by mbaudis** [comment]
Progenetix test example, including schema link from [specification-v2-blocks](https://github.com/ga4gh-beacon/specification-v2-blocks):

* <https://progenetix.org/cgi/bycon/bycon/filteringTerms.py>
