### ISSUE TITLE
Term `variantInSample` is confusing, `g_variants` is odd

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#45]
The current v2 version contains 2 paths, objects and associated classes for genomic variants:

1. `/g_variants`  with `GenomicVariantResponse` => `VariantReponseResults` => `[variant, variantAnnotations ...]`
2. `/variants_in_sample` with `VariantInSampleResponse` => `VariantInSampleResponseResults` => (some variant schema)

IMO the naming is confusing. Instead of `variants_in_sample` it would be clearer to use `variant_instance(s)` or `observed_variant(s)`. So, instead of:

```
  /g_variants/{id}/variants_in_sample:
    post:
      description: |
        Get the variants in sample in which this variant is found.
```
... it would be:
```
  /g_variants/{id}/variant_instances:
    post:
      description: |
        Retrieve all instances of this genomic variant.
```
Also, `g_variant` is not the best name. We're only covering genomic variants and don't use the `g_` anywhere else. If -> should be spelled out. So, other options would be:

* `variants`
  - since "variant" is used everywhere else in the composed parameter names etc.
* `variant_prototypes` (or something similar?)
  - corresponds to the "not the observation itself is meant but the observation of instances of this kind of variant, or information about it"

So probably easiest (not cleanest) just to drop the `g_` and then work on the documentation, that with `variant` something akin to "line in VCF" is being meant.

**Comment by clauw87** [comment]
I agree with the dropping g_ .
And with the fact of the second description of VariantInSample being more descriptive. 
Also true, the name VariantInstance could be more descriptive than VariantInSample.

**Comment by jrambla** [comment]
We put the "g_" because we could end up having "protein variants" and then we are in trouble. 
I know we are not used to that, because of our bias, do we?

**Comment by jrambla** [comment]
And, IMHO, "variant_in_sample" seems much more aligned to what clinical bioinformaticians are used to than "variant_instance" that seems to me a "researcher-like term".

**Comment by clauw87** [comment]
Jordi, but it is true that, given that the Variant in Sample comes from Analysis indeed, it could be that 1 Sample has many Analyses if it is subjected to two different sequencing technologies and analysis etc and gives different variants, and then, if we are showing them as in the schema, whatever is coming out of an analysis it will be strictly not Variant in Sample but Variant in Analysis, which at the time I think seemed awkward to us and we left Variants in Sample, but it is strictly not right.

**Comment by clauw87** [comment]
The variant instance name, when given a thought, seems right to me,.bc it refers to a Variant found in this and that special circumstances that are recorded there,.individual, sample, run, analysis, etc

**Comment by mbaudis** [comment]
O.k. - originally posted this just in another thread. cross-posting ...

----

Well, "variant_in_sample" just sounds odd. Either it is jaust a `variant` - but this is being squatted on by `g_variant` ... as not being a specific observation but a kind of "prototypical variant" with **instances** being observed.

Just for you - __I hope this doesn't get public__ - the whole concept of seeing a variant in a data collection as anything but **the observation in a sample using some methods** is ridiculous. A.k.a. VCF.

The "we store primary observations of variants as calls of for this variant in a sample" (VCF) concept is not tenable, scalable. There should be a strict separation between an observed genotypic morsel and its interpretation. And don't store "variant" frequencies, ever. These are archaic concepts which helped to use 1kg ("1000" genomes) but should have been ditched a while ago.

So a `variant` should always be a single allelic (or quantitative... etc. like CNV) _observation_ from a single experiment/sample ... And you can attach all technical, circumstantial information to it (like your QC, purity, clinical data).

In contrast to this, there are the "variant_prototypes", e.g. providing information  about what knowledge has been assembled regarding "identical" variants (or, more precisely, "equivalent" variants). So ClinGen, your "line in VCF" variants etc.

The Beacon model should be to clearly match against variant instances (e.g. de-normalized VCFs w/ single sample, single allele variants) and then do secondary evidence matching. And also the other way; query prototypes & get the instances. But clearly modeled as such.

So, if I could, I would just make `variant` eq `variant_instance` (a.k.a. "variant_in_sample"). And  then have another object for those `annotated_variant` == `variant_prototype` ... or whatever you call it.

Now, this may be flipped - `variant` could be the "prototype (rsid and all), and the primary variant is then `variant_instance`. No problem with that - just be clear about it.

Doesn't change a thing (well) for querying since going by position, variantType ... etc. you match the same connected data. Just the delivery is different.

But anything else is just ... hurting. I guess with a clean model - which we don't have here yet! - life could be much easier.

**Comment by jrambla** [comment]
Could we keep *this* issue as the discussion for "g_Variant" vs. "Variant" and discuss the "VariantInSample" (and the model) in the other issue?

**Comment by sdelatorrep** [comment]
Please, let me know what the conclusion is. 
This will affect #42: if we finally choose to use `/variant`, then the object named `GenomicVariantResponseContent` (and any other) should be renamed to `VariantResponseContent`.

**Comment by jrambla** [comment]
We would revisit that, if necessary, after the changes we plan to introduce in the Beacon v2 Model draft4.
