### ISSUE TITLE
AlternativeSchema and oneOf issue

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/specification-v2#56]
Hello,
There is a logical issue with an AlternativeSchema object.  
Currently we have something like:
```json
{
    "definitions": {
        "VariantIdentification": {
            "properties": {
                "variantId": {
                    "type": "string"
                }
            }
        },
        "AlternativeSchema": {
            "type": "object"
        }
    },
    "oneOf": [
        {"$ref": "#/definitions/AlternativeSchema"},
        {"$ref": "#/definitions/VariantIdentification"}
    ]
}
```
Note that while the schema itself is valid, something like:
```json
{
    "variantId": "gattaca"
}
```
will fail to validate, because it validates with both schemas and **oneOf** must validate only against exactly one only. 
The solution would be:
1. make "variantId" identifier **required**
2. add some **required** property into the "AlternativeSchema" (i.g. "externalSchemaURL" : "string")
or
3. forbid "variantId" identifier 

Example:
```json
{
    "definitions": {
        "VariantIdentification": {
		    "properties": {
                "variantId": {
                    "type": "string"
                }
            },
            "required": ["variantId"]
        },
        "AlternativeSchema": {
            "type": "object"
        }

    },
    "oneOf": [
        {"allOf": [{ "$ref": "#/definitions/AlternativeSchema"}],
         "not": { "required": [ "variantId" ] }
        },
        {"$ref": "#/definitions/VariantIdentification"}
    ]
}
```
Cheers,

Dmitry

P.S. or just use "anyOf"... :-)

**Comment by sdelatorrep** [comment]
Hi @redmitry. What if we use `anyOf` instead of `oneOf` and we explain in the description that you **must** only use one of these? We've already faced some other limitations of OpenAPI that we need to clarify in the description.
From the OpenAPI documentation:
> 
    oneOf – validates the value against exactly one of the subschemas
    allOf – validates the value against all the subschemas
    anyOf – validates the value against any (one or more) of the subschemas

Because I don't think it's a valid option in our context to force the alternative schema to **not** include some property (e.g. the alternative schema might extend the content of the default schema), and I'm not sure if we can force to have some required...

**Comment by redmitry** [comment]
Hi @sdelatorrep. "anyOf" would use only one of two anyway. The only difference is that it can validate with both at the same time. In the structural description this makes little sense: anyOf (any (object) or something (VariantIdentification).
Note that without any "required" property **any** Json Object is also valid VariantIdentification.
For all such cases I would put the "id" fields required and use anyOf. This way an implementer may choose to use Schema Object or generic JsonObject on the basement of the "valiantId" property...

**Comment by sdelatorrep** [comment]
But this way you will be requiring all alternative schemas to have an `id`, which I'd say it's something we can't do (e.g. current Phenopacket's and Variant Representation schemas for Variant Identification won't validate because none of them have an `id` field).

**Comment by redmitry** [comment]
No. the requirement for the id is for the provided schemas. 
Without "required" properties in the VariantIdentification, any JsonObject fulfil the schema.
this way we do not need a choice at all... The question is what we want do say with the choice.

**Comment by sdelatorrep** [comment]
Can you create a PR with your proposal? Because I think I'm not understanding it :)

**Comment by redmitry** [comment]
There are two parts:
https://github.com/ga4gh-beacon/specification-v2/pull/57
https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/27

the second pull is just a suggestion as we need a way to distinguish between an arbitrary and default schemas...
