### ISSUE TITLE
Response type and paths

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#58]
While the response types are documented in the individual path's descriptions

* e.g. https://github.com/ga4gh-beacon/specification-v2/blob/develop/beacon.yaml#L165

... they should (IMO) be specified directly in the `paths` schemas? I.e. a service should be able to map a response directly from the path. There is a `schema` parameter, but AFAIK this is not the same as spec'ing the response itself & there could be conflicts.

**Comment by sdelatorrep** [comment]
I'm sorry @mbaudis, but I don't get what you are proposing. Could you write an example, please? Thanks!

**Comment by mbaudis** [comment]
@sdelatorrep When a server interprets the REST path it cannot know from the schema which response it should provide.

That e.g. the response should be an `IndividualResponse` is usually annotated in the description, but not formalized. 

```
  /individuals/{id}:
    post:
      description: |
        Get an individual (`IndividualResponse`) by its Id.
      operationId: postIndividualById
      tags:
        - Endpoints
      parameters:
        - name: id
...
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: false
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
```

**Comment by mbaudis** [comment]
@sdelatorrep So IMO there should be a specification in the path schemas for `responseSchema: "IndividualResponse"` or similar. Or do I miss another way this is being specified? It is not clear that `/individuals` leads to `IndividualResponse`.

**Comment by sdelatorrep** [comment]
OK, then we shouldn't have accepted PR #46 as it was. It is possible to do what you say by creating as many `Success`, `BadRequest`, `Unauthorized` and `Forbidden` response types, as entities we have: `VariantScucess`, `VariantBadRequest`, `VariantUnauthorized`, `VariantForbidden`, etc.
I thought doing this would be too verbose and would make it harder to maintain, but you are totally right that you have to read the description in order to know what entity will be returned, but OpenAPI has no other way to do this easier, unluckily.

**Comment by mbaudis** [comment]
@sdelatorrep I wouldn't restrict to OpenAPI as the envelope, then. One could add a custom parameter? Is a step up from just having it in the text ... Right now one has to hand-craft this :-(

**Comment by jrambla** [comment]
This has been addressed in the Beacon Framework and Model approach.
