### ISSUE TITLE
Beacon API info objects debris

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/specification-v2#61]
Hello,

We have several "info" endpoints:
~~~yaml
"/"
"/info"
"/service-info"
"/datasets"
~~~
In my understanding `/service-info` endpoint is to support _GA4GH service-info_ spec. So far so good.
`/` is the `/info` endpoint to return Beacon info by default (aka homepage).
In the `/info` there are two query parameters - "**model**" it says in this case it is the same as `/service-info` and "**requestedSchema**" - beacon-type info.
What is the reason to support _GA4GH serice-info_ object in the `/info` endpoint?
What is the reason to provide "**model**" string parameter if the format in this case is fixed by _GA4GH service-info_ spec?

`/info` (with **requestedSchema**=???) and `/datasets` return the same "**InfoResponse**" object which is defined as...
~~~yaml
oneOf:
  - $ref: '#/components/schemas/InfoResponseContent'
  - $ref: '#/components/schemas/DatasetResponseContent'
~~~
IMO it is much clearly and easily to implement when 
`/info` returns "**InfoResponseContent**" and 
`/dataset` returns "**DatasetResponseContent**"
The "**meta**" property from "**InfoResponse**" just go to both "**ResponseCoontents**"

What is your opinions?

Dmitry.

**Comment by mbaudis** [comment]
+1 for putting this on the radar - too much "we do legacy, too" here. No constructive comments but a correction:

> / is the /info endpoint to return Beacon info by default (aka homepage).

... actually not. Would IMO be a good opportunity to define `/` as the non-machine, human readable (aka homepage) target & therefore leading to fewer errors; but so far this hasn't been the case with previous incantations (sic) using it for the API info and the UI having a separate URL specified in `info` / `service-info`.

But I'm open to other solutions. There could be a defined/required UI path instead.

**Comment by jrambla** [comment]
@sdelatorrep I'm not able to answer the "oneOf" question. Do you have that fresh in your mind?

**Comment by jrambla** [comment]
For "/info" pletora of options:

1. for the "/info" vs "/":  I was always in favor of explicit endpoints, hence info was my preference. But given that "/" should also return something, "Beacon info" was the obvious option. It has been argued that if "/" is there, then "/info" is not required. But that is inverting the reasoning and then we lose the "explicit" endpoint. Thus, I've suggested to keep both.
2. "/service-info" is there per GA4GH request. It is not following the structure of all other Beacon responses. Hence we must keep it, but we shouldn't rely on it.
3. So, we end up having an "/info" endpoint that is using the Beacon format. All other entities allow for alternative schemas, hence we believed that "/info" should also do so, and opening the door to other types of schemas like FAIRDataPoints, or W3C Service or whichever. Consequence, adding the `requestedSchema `parameter.
4. In my memory, the` "model"` parameter is the previous incarnation of the requestedSchemas et al. Maybe @sdelatorrep can also confirm that.

**Comment by mbaudis** [comment]
@jrambla So how about `/` being the UI? `info` already there, nnd UI is what users go to. It is a bit of a pain not to have Beacon (sub)domain providing the UI itself.

And otherwise I would suggest a hard-coded `/ui` instead of relegating this to the (service-)info.

**Comment by jrambla** [comment]
Sorry, I'm always struggling with these issues that address different aspects.
IMHO, we shouldn't mix API endpoints with UI endpoints.
I suggest using "https://onebeacon.org/" to host the UI and "https://onebeacon.org/api" (e.g,) to host the API, therefore you are free to add any stuff as pages in the UI and keep the API endpoints also free.
Makes sense?

**Comment by mbaudis** [comment]
@jrambla Fine with that; actually ~ what we've switched to (though `/beacon` ATM). Still, `/info` == `/` is confusing. Why not ditch `/info`? And keep `/service-info` as the specific GA4GH one.

**Comment by Tom-Shorter** [comment]
This is one of the topics I have wanted to raise in the API scout group, and very briefly mentioned in the first one. 

I would be in favour of removing the /info and /service-info endpoints completely and just using / as the info end point but I do understand that this is something that can't happen as /service-info is a GA4GH standard and / is not an explicit endpoint

I would instead suggest that we get rid of / and /info as info endpoints and solely use /service-info. I'm not aware of a reason for having to keep /info but please let me know if there is one.

This then leaves / available, @mbaudis recommended that the UI could sit here, I agree with @jrambla that the UI should sit on it's own distinct endpoint. Instead / could be used as a human readable page giving information about the beacon project and some info about the individual beacon the user is viewing. This could include a tutorial on how to get the most out of a beacon, example queries or links to human readable versions of the now /service-info, / filtering_terms, the UI etc.

I also agree with @redmitry regarding the /info and /datasets content, currently /datasets shows a subset of information within the /info endpoint so there is no need for it's existence. I like the idea of separating the content between the two endpoints but I think a better solution would be to show a very limited amount of information about datasets from /info and then have a more in depth response from /datasets. I know @jrambla has mentioned about using HATEOAS concepts and I believe it would be very useful within the datasets section of /info. /info can use the HATEOAS style of response to return links to the /datasets endpoint, which could be expanded to include things such as /datasets/{id}, /datasets/{id}/dataUseConditions and in the filter scout group we have implemented /datasets/{id}/filtering_terms. Using this method the /info end point would still contain all of the information it currently does but in a much more condensed manner and the /datasets endpoints can be queried for the full details if needed.

**Comment by sdelatorrep** [comment]
@jrambla , `model` parameter was requested to be added, so it was compatible with the Beacon Network spec (its `/info` endpoint defines this parameter).

**Comment by jrambla** [comment]
Open parts of the discussion are brought into https://github.com/ga4gh-beacon/beacon-framework-v2/issues/10
