### ISSUE TITLE
/biosamples response is missing a datasetID field

### ISSUE THREAD

**Issue by Tom-Shorter** [ga4gh-beacon/specification-v2#67]
There is currently no way to identify which dataset an individual biosample came from, `/individuals` and `/g_variants` both have a datasetID field within the response object for individual results so it seems an oversight that it is missing from `/biosamples`.

**Comment by mbaudis** [comment]
That is probably just an oversight, but in the end related to https://github.com/ga4gh-beacon/specification-v2/issues/63. So one would wrap `datasetAlleleResponses` for different datasets, but for the biosamples or individuals then indicate their datasetId per item? Then we need this for the `VariantInSample`  and any other object which can end up in `response.results`, too.

Or responses are always for a single dataset, with the possible exception of a generic response as in the old days.

Or in `response.results` are __always__ lists of `datasetResponse` objects.

**Comment by mbaudis** [comment]
... also, to have a `datasetId` in a given `biosample`, `individual`, `variantInSample` response is ugly; it is __NOT__ part of the native object schema and has to be overloaded for the response. So if a `/biosamples` response contains data from multiple datasets those should be wrapped in dataset specific objects.

**Comment by jrambla** [comment]
The rationale behind the model is: "we have two types of Beacons: evidence/knowledgeBase and Case/individuals".
The first one is represented by Dataset>Variant, the second one by Dataset>Individual (extended later with Cohort>Individual.
That is the reason that no other entity is having a DatasetId on it.
Michael's case is where the Beacon is made by samples from cell cultures (let's say) and it doesn't fit to one or the other.
As per our initial exploration that doesn't seem to be a "majority" case, and I have no feeling of how many other case we'll find.
Hence, we suggested Michael to extract the attributes from the individual from the samples and create these "virtual" individuals. Which I believe could make sense anyway, as thus you can relate samples from the same individual and such.
`datasetAlleleResponse` should be deprecated if it is not already.

**Comment by mbaudis** [comment]
@jrambla That's not what is meant here? This was about identification of a `biosample` <-> `dataset` relation.

In any case, it gets a bit confusing; but IMO this should be resolved through #68 (which I see as the most logical solution, until @jrambla tells me why this wouldn't work ...).

**Comment by sdelatorrep** [comment]
Hi @Tom-Shorter. I think this is solved with the resultSet wrapper, right? If not, please, reopen this issue. Thanks!
