### ISSUE TITLE
Replace offset-based pagination by a cursor-based approach

### ISSUE THREAD

**Issue by jlfrueda** [ga4gh-beacon/specification-v2#70]
While implementing the beacon we have meet several problems regarding pagination, and we believe the current approach can be improved with just a few trivial changes.

Some of our systems organize the data in a way that is not well suited to offset-based paging, for performance reasons. Even not considering this, there are not always a direct mapping between our backend entities and those of the beacon, so in many cases we have to "build" synthetic entities, maybe post-filtering the combined entities when the query criteria involve several of them, in the sense of a JOIN, or when we don't have filters completely matching those of the specification.

In these cases, offset-based paging is inadequate or even impossible without counting results from the start, including those of the preceding pages, as sometimes we cannot anticipate how many results will generate an entity, given a query, for previous pages, except by actually performing the queries. This leads to an extremely inefficient implementation in the sense of a Schlemiel the painter's algorithm.

An imaginary illustrative example could be a system that stores variants by their RefSeq. For example

	{ id: "rs371609562", reference: "TTTT", alternates: ["T", "TT"] }

If an API requires scalar alternates, such an entity would generate two results in a variant query:

	{ id: ???????, rsId: "rs371609562", reference: "TTTT", alternate: "T" }	
	{ id: ???????, rsId: "rs371609562", reference: "TTTT", alternate: "TT" }

There is no easy way in such a system to query for the n-th page, but there are extremely efficent ways to query for the next page.

This is a common topic in big data systems, and we believe it can be a widespread problem that will limit many potential backends.

To solve this we propose replacing offset-based pagination by a value- or cursor- based approach, which we use in most of our developments.

So, instead of setting limit and skip values,

	{ ..., limit: 100, skip: 500 }

the queries should expect a limit and a next_page token.

	{ ..., limit: 100, nextPage: <system-depended-token-for-next-page> }  -> { ...<response>, nextPage: <system-depended-token-for-next-page> }

If this token is not specified, the first page should be returned. The response should include a next_page token to be included in the next request.

Paging this way, not much is lost for the client, mostly the ability to skip pages, which may not be that useful in most use cases. One can always use page numbers as next-page tokens for a trivial fallback.

But implementors can gain a lot of flexibility building their queries, and most systems will see an increase in performance and very efficient streaming of results with minimal impact on performance, including not only big data systems or, as in our case, distributed ones, but also SQL-based ones, as value-based paging allows indexes to be used to skip results. Both highly desirable benefits that can help a fast adoption of the beacon.

**Comment by Tom-Shorter** [comment]
I fully support this approach to pagination, as per my pagination issue #26, I envisioned a similar problem for beacons which contained more than one dataset. In short how do you know which dataset the results from page X come from without having to query every dataset sequentially?

If I was to implement this approach my `nextPage` token would look something like `datasetID-uniqueIndex`. I think this is quite a standard approach where the token will tell you which dataset to start with when looking for the next page of results and also to only return results after the unique index specified.

Aggregation of data (such as in /g_variant responses) within completely separate databases will still be an issue for this approach, the beacon will either need to pre-calculate any aggregation data info and store this, or for any query submitted to a beacon, the beacon would internally need to return all results from all queried datasets, aggregate the results as part of the query process and then respond with only the results specified within the pagination.

Both of the above solutions could be used effectively in different situations, the first solution would be slightly more complex (especially with datasets that are frequently updated) but would be more suitable for larger beacons or heavily utilised beacons where keeping response times as low as possible is a priority. The second solution would be effective for smaller beacons or for beacons which are not as frequently used, this solution cuts out the need to pre-calculate any aggregation of data but each query would require longer to process.

**Comment by jrambla** [comment]
Moved to Beacon framework v2 (https://github.com/ga4gh-beacon/beacon-framework-v2/issues/9)
