### ISSUE TITLE
Support referenceName in chr_ pattern?

### ISSUE THREAD

**Issue by jimmyhli** [ga4gh-beacon/specification-v2#76]
Support referenceName in chr_ pattern?

It looks like some pipelines are outputting VCFs with referenceNames in a chr_ pattern, e.g., chr1 instead of 1, would the schema take this into account?

**Comment by mbaudis** [comment]
@haoyuanli This is no issue for the specification itself which is agnostic of whatever format is used to store the data, but can rather be an issue for implementations. Beacon is _not_ a protocol to query VCFs, but (reference) implementations may support VCFs and then consider this.

We will provide more documentation for queries & there will be some query testing/debugging tools; but I'm for one against alternatives in the query itself.

**Comment by jimmyhli** [comment]
Thanks for the quick reply. Our API definition file though, has defined that referenceName to be one of ["1", "2", ....], And implementation that strictly follows the API spec would reject "chr1" as invalid. Are you suggesting that implementation could choose to accept "chr1" if they wish? Thanks

**Comment by jrambla** [comment]
The use of human readable reference names vs reference sequence names (like NCxxxxx.1) would be debated in the Beacon v2 Model draft4. I'm closing this issue in the hope that the discussion there would solve the doubts/suggestions expressed here.
