### ISSUE TITLE
[typo] IndividualResponseContent.results[] : IndividualResponseResults

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/specification-v2#77]
Hello,

The "**results**" property in the '**IndividualResponseContent**' is an array of '**IndividualResponseResults**' objects.
The '**IndividualResponseResults**' object is singular (defaults to '**Individual**') and shouldn't be named plural.
Suggest: '**IndividualResponseResults**' -> '**IndividualResponseResult**'

Cheers,

Dmitry

**Comment by jrambla** [comment]
Should be addressed in the Beacon Framework + Model in draft4, but please double check.
