### ISSUE TITLE
HandoverType should be an instance of OntologyTerm

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2#78]
`HandoverType` is [specified as a separate component](https://github.com/ga4gh-beacon/specification-v2/blob/51f3e1d5aad5d1a160446ce6bb0f2c6a429ba7e1/beacon.yaml#L2638). However, structurally it represents just an [instance of an `OntologyTerm`](https://github.com/ga4gh-beacon/specification-v2/blob/51f3e1d5aad5d1a160446ce6bb0f2c6a429ba7e1/beacon.yaml#L2695).

This - and other similar cases in the schemas - should just be normalized to use the `OntologyTerm` class, with optional extensions.

**Comment by jrambla** [comment]
This was separated as we expect to eventually define other types that are not ontology base, e.g. a DRS or an htsget handover type.
