### ISSUE TITLE
Id property names inconsistency

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/specification-v2#79]
Hello,

There is an inconsistency in some ids properties:
pedigreeID, exposureID but,
phenotypeId, treatmentId, etc.

IMHO should be 'pedigreeId' and 'exposureId'.

Cheers,

Dmitry

**Comment by sdelatorrep** [comment]
Hi @redmitry, the right repository for this issue is https://github.com/ga4gh-beacon/specification-v2-default-schemas, not here :)

**Comment by redmitry** [comment]
oops. sorry
