### ISSUE TITLE
Add endpoints

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification-v2#9]
* `/schemas`: to list the schemas supported by this Beacon
* `/filtering_terms`: to list the ontologies and custom dictionaries supported by this Beacon
* `/access_levels`: to list the access levels for each field
* more?

**Comment by mbaudis** [comment]
@sdelatorrep Is "schemas" not too broad? Does this refer to request types only, or is this more general? I would suggest `request_types`:

* `beacon_cnv_request`
* `beacon_allele_request`
* ...

**Comment by sdelatorrep** [comment]
The idea of the `/schemas` endpoint is to show all the schemas and versions supported by the beacon, so something similar to this:
```json
{
   "Variant":[
      "beacon-variant-v0.1",
      "beacon-variant-v1.0",
      "variant-representation-v1.0"
   
],
   "VariantAnnotation":[
      "beacon-variant-annotation-v1.0"
   
],
   "Biosample":[
      "beacon-biosample-v1.0",
      "schemablocks-biosample-v1.0",
      "phenopackets-biosample-v1.0",
      "phenopackets-biosample-v1.5"
   
]
}
```

**Comment by jrambla** [comment]
Let's add the `schemas` endpoint, and open up a new issue for each of the others.
